id: IDCF0C515
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:33:24+00:00'
last_modified: '2022-06-08T17:56:07.171230+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21830
  title: སྐད་བརྡ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D881:
      image_group_id: I1KG21935
      title: Volume 1 of skad brda rig pa'i spyi bshad/
      total_pages: 354
      order: 1
      base_file: D881.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
