id: P008030
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:56:38.198833
source_metadata:
  id: bdr:W1KG21830
  title: སྐད་བརྡ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  volumes:
    5f155a3ba6534802a526a0dd3510da67:
      image_group_id: I1KG21935
      title: Volume 1 of skad brda rig pa'i spyi bshad/
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
