id: P008030
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21830
  title: སྐད་བརྡ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  volumes:
    7eb2bdce2be54895b4e814f1b5feff94:
      image_group_id: I1KG21935
      title: ''
      volume_number: 1
      total_pages: 354
ebook_metadata:
  title: སྐད་བརྡ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  sku: P008030
  cover: cover.jpg
  layers:
  - pagination
